{% set name = "pypromice" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a130be808d21ab8701a064b3e2d99879ae0a51d88d6e38e331bc15d2929dd60

build:
  entry_points:
    - get_promice_data = pypromice.get.get_promice_data:get_promice_data
    - get_l0tx = pypromice.tx.get_l0tx:get_l0tx
    - get_l3 = pypromice.process.get_l3:get_l3
    - join_l3 = pypromice.process.join_l3:join_l3
    - get_watsontx = pypromice.tx.get_watsontx:get_watsontx
    - get_bufr = pypromice.postprocess.get_bufr:get_bufr
    - get_msg = pypromice.tx.get_msg:get_msg
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.23.0
    - pandas >=1.5.0
    - xarray >=2022.6.0
    - toml
    - scipy >=1.9.0
    - scikit-learn >=1.1.0
    - bottleneck
    - netcdf4
    - pydataverse

test:
  imports:
    - pypromice
  commands:
    - pip check
    - python -m unittest discover pypromice
  requires:
    - pip

about:
  home: https://github.com/GEUS-Glaciology-and-Climate/pypromice
  summary: A toolbox for handling and processing PROMICE (Programme for Monitoring of the Greenland Ice Sheet) and GC-Net (Greenland Climate Network) automated weather station data
  license: GPL-2.0
  license_file: LICENSE.txt
  doc_url: https://pypromice.readthedocs.io
  dev_url: https://github.com/GEUS-Glaciology-and-Climate/pypromice

extra:
  recipe-maintainers:
    - PennyHow
    - ladsmund
    - patrickjwright
    - mankoff
