{% set name = "pypromice" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a16e52b5253b110b1b8712d2af9a574579317ace93d5cb41712f71e2abec29ed

build:
  entry_points:
    - get_promice_data = pypromice.get.get_promice_data:get_promice_data
    - get_l0tx = pypromice.tx.get_l0tx:get_l0tx
    - get_watsontx = pypromice.tx.get_watsontx:get_watsontx
    - join_l2 = pypromice.process.join_l2:main
    - join_l3 = pypromice.process.join_l3:main
    - get_l2 = pypromice.process.get_l2:main
    - get_l2tol3 = pypromice.process.get_l2tol3:main
    - make_metadata_csv = pypromice.postprocess.make_metadata_csv:main
    - get_bufr = pypromice.postprocess.get_bufr:main
    - create_bufr_files = pypromice.postprocess.create_bufr_files:main
    - bufr_to_csv = pypromice.postprocess.bufr_to_csv:main
    - get_msg = pypromice.tx.get_msg:get_msg
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - pip
  run:
    - python >=3.10
    - numpy >=1.23.0
    - pandas >=1.5.0
    - xarray >=2022.6.0
    - toml
    - scipy >=1.9.0
    - scikit-learn >=1.1.0
    - bottleneck
    - netcdf4
    - pydataverse
    - eccodes

test:
  imports:
    - pypromice
  commands:
    - python3 -m unittest discover tests
  requires:
    - pip

about:
  home: https://github.com/GEUS-Glaciology-and-Climate/pypromice
  summary: A toolbox for handling and processing PROMICE (Programme for Monitoring of the Greenland Ice Sheet) and GC-Net (Greenland Climate Network) automated weather station data
  license: GPL-2.0
  license_file: LICENSE.txt
  doc_url: https://pypromice.readthedocs.io
  dev_url: https://github.com/GEUS-Glaciology-and-Climate/pypromice

extra:
  recipe-maintainers:
    - PennyHow
    - ladsmund
    - patrickjwright
    - mankoff
